services:
  - type: web
    name: nextstep-ai
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
